// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: authbase.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Banned        bool                   `protobuf:"varint,2,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_authbase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_authbase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_authbase_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_authbase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_authbase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_authbase_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Role) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_authbase_proto protoreflect.FileDescriptor

const file_authbase_proto_rawDesc = "" +
	"\n" +
	"\x0eauthbase.proto\x12\n" +
	"varso_auth\"2\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06banned\x18\x02 \x01(\bR\x06banned\"N\n" +
	"\x04Role\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissionsB\x0fZ\rclient/modelsb\x06proto3"

var (
	file_authbase_proto_rawDescOnce sync.Once
	file_authbase_proto_rawDescData []byte
)

func file_authbase_proto_rawDescGZIP() []byte {
	file_authbase_proto_rawDescOnce.Do(func() {
		file_authbase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authbase_proto_rawDesc), len(file_authbase_proto_rawDesc)))
	})
	return file_authbase_proto_rawDescData
}

var file_authbase_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authbase_proto_goTypes = []any{
	(*User)(nil), // 0: varso_auth.User
	(*Role)(nil), // 1: varso_auth.Role
}
var file_authbase_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authbase_proto_init() }
func file_authbase_proto_init() {
	if File_authbase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authbase_proto_rawDesc), len(file_authbase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authbase_proto_goTypes,
		DependencyIndexes: file_authbase_proto_depIdxs,
		MessageInfos:      file_authbase_proto_msgTypes,
	}.Build()
	File_authbase_proto = out.File
	file_authbase_proto_goTypes = nil
	file_authbase_proto_depIdxs = nil
}
