// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: authrequests.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserRequest) Reset() {
	*x = BanUserRequest{}
	mi := &file_authrequests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserRequest) ProtoMessage() {}

func (x *BanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserRequest.ProtoReflect.Descriptor instead.
func (*BanUserRequest) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{0}
}

type BanUserResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BannedUserDiscordId string                 `protobuf:"bytes,1,opt,name=banned_user_discord_id,json=bannedUserDiscordId,proto3" json:"banned_user_discord_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BanUserResponse) Reset() {
	*x = BanUserResponse{}
	mi := &file_authrequests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserResponse) ProtoMessage() {}

func (x *BanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserResponse.ProtoReflect.Descriptor instead.
func (*BanUserResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{1}
}

func (x *BanUserResponse) GetBannedUserDiscordId() string {
	if x != nil {
		return x.BannedUserDiscordId
	}
	return ""
}

type DiscordLoginRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	InternalLoginAuthSecret string                 `protobuf:"bytes,1,opt,name=internal_login_auth_secret,json=internalLoginAuthSecret,proto3" json:"internal_login_auth_secret,omitempty"`
	DiscordUserId           string                 `protobuf:"bytes,2,opt,name=discord_user_id,json=discordUserId,proto3" json:"discord_user_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DiscordLoginRequest) Reset() {
	*x = DiscordLoginRequest{}
	mi := &file_authrequests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordLoginRequest) ProtoMessage() {}

func (x *DiscordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordLoginRequest.ProtoReflect.Descriptor instead.
func (*DiscordLoginRequest) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{2}
}

func (x *DiscordLoginRequest) GetInternalLoginAuthSecret() string {
	if x != nil {
		return x.InternalLoginAuthSecret
	}
	return ""
}

func (x *DiscordLoginRequest) GetDiscordUserId() string {
	if x != nil {
		return x.DiscordUserId
	}
	return ""
}

type DiscordLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordLoginResponse) Reset() {
	*x = DiscordLoginResponse{}
	mi := &file_authrequests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordLoginResponse) ProtoMessage() {}

func (x *DiscordLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordLoginResponse.ProtoReflect.Descriptor instead.
func (*DiscordLoginResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{3}
}

func (x *DiscordLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_authrequests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByDiscordIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByDiscordIdResponse) Reset() {
	*x = GetUserByDiscordIdResponse{}
	mi := &file_authrequests_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByDiscordIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByDiscordIdResponse) ProtoMessage() {}

func (x *GetUserByDiscordIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByDiscordIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByDiscordIdResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByDiscordIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type InternalLoginRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	InternalLoginAuthSecret string                 `protobuf:"bytes,1,opt,name=internal_login_auth_secret,json=internalLoginAuthSecret,proto3" json:"internal_login_auth_secret,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InternalLoginRequest) Reset() {
	*x = InternalLoginRequest{}
	mi := &file_authrequests_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalLoginRequest) ProtoMessage() {}

func (x *InternalLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalLoginRequest.ProtoReflect.Descriptor instead.
func (*InternalLoginRequest) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{6}
}

func (x *InternalLoginRequest) GetInternalLoginAuthSecret() string {
	if x != nil {
		return x.InternalLoginAuthSecret
	}
	return ""
}

type InternalLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalLoginResponse) Reset() {
	*x = InternalLoginResponse{}
	mi := &file_authrequests_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalLoginResponse) ProtoMessage() {}

func (x *InternalLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalLoginResponse.ProtoReflect.Descriptor instead.
func (*InternalLoginResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{7}
}

func (x *InternalLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_authrequests_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_authrequests_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EasyRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EasyRegisterRequest) Reset() {
	*x = EasyRegisterRequest{}
	mi := &file_authrequests_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EasyRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EasyRegisterRequest) ProtoMessage() {}

func (x *EasyRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EasyRegisterRequest.ProtoReflect.Descriptor instead.
func (*EasyRegisterRequest) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{10}
}

func (x *EasyRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EasyRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EasyRegisterResponse) Reset() {
	*x = EasyRegisterResponse{}
	mi := &file_authrequests_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EasyRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EasyRegisterResponse) ProtoMessage() {}

func (x *EasyRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EasyRegisterResponse.ProtoReflect.Descriptor instead.
func (*EasyRegisterResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{11}
}

func (x *EasyRegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UsernameOrEmail string                 `protobuf:"bytes,1,opt,name=username_or_email,json=usernameOrEmail,proto3" json:"username_or_email,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_authrequests_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{12}
}

func (x *LoginRequest) GetUsernameOrEmail() string {
	if x != nil {
		return x.UsernameOrEmail
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_authrequests_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{13}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UnbanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanUserRequest) Reset() {
	*x = UnbanUserRequest{}
	mi := &file_authrequests_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanUserRequest) ProtoMessage() {}

func (x *UnbanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanUserRequest.ProtoReflect.Descriptor instead.
func (*UnbanUserRequest) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{14}
}

type UnbanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDiscordId string                 `protobuf:"bytes,1,opt,name=user_discord_id,json=userDiscordId,proto3" json:"user_discord_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanUserResponse) Reset() {
	*x = UnbanUserResponse{}
	mi := &file_authrequests_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanUserResponse) ProtoMessage() {}

func (x *UnbanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authrequests_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanUserResponse.ProtoReflect.Descriptor instead.
func (*UnbanUserResponse) Descriptor() ([]byte, []int) {
	return file_authrequests_proto_rawDescGZIP(), []int{15}
}

func (x *UnbanUserResponse) GetUserDiscordId() string {
	if x != nil {
		return x.UserDiscordId
	}
	return ""
}

var File_authrequests_proto protoreflect.FileDescriptor

const file_authrequests_proto_rawDesc = "" +
	"\n" +
	"\x12authrequests.proto\x12\n" +
	"varso_auth\x1a\x0eauthbase.proto\"\x10\n" +
	"\x0eBanUserRequest\"F\n" +
	"\x0fBanUserResponse\x123\n" +
	"\x16banned_user_discord_id\x18\x01 \x01(\tR\x13bannedUserDiscordId\"z\n" +
	"\x13DiscordLoginRequest\x12;\n" +
	"\x1ainternal_login_auth_secret\x18\x01 \x01(\tR\x17internalLoginAuthSecret\x12&\n" +
	"\x0fdiscord_user_id\x18\x02 \x01(\tR\rdiscordUserId\",\n" +
	"\x14DiscordLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"7\n" +
	"\x0fGetUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.varso_auth.UserR\x04user\"B\n" +
	"\x1aGetUserByDiscordIdResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.varso_auth.UserR\x04user\"S\n" +
	"\x14InternalLoginRequest\x12;\n" +
	"\x1ainternal_login_auth_secret\x18\x01 \x01(\tR\x17internalLoginAuthSecret\"-\n" +
	"\x15InternalLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\")\n" +
	"\x13EasyRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x14EasyRegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"V\n" +
	"\fLoginRequest\x12*\n" +
	"\x11username_or_email\x18\x01 \x01(\tR\x0fusernameOrEmail\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x12\n" +
	"\x10UnbanUserRequest\";\n" +
	"\x11UnbanUserResponse\x12&\n" +
	"\x0fuser_discord_id\x18\x01 \x01(\tR\ruserDiscordIdB\x0fZ\rclient/modelsb\x06proto3"

var (
	file_authrequests_proto_rawDescOnce sync.Once
	file_authrequests_proto_rawDescData []byte
)

func file_authrequests_proto_rawDescGZIP() []byte {
	file_authrequests_proto_rawDescOnce.Do(func() {
		file_authrequests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authrequests_proto_rawDesc), len(file_authrequests_proto_rawDesc)))
	})
	return file_authrequests_proto_rawDescData
}

var file_authrequests_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_authrequests_proto_goTypes = []any{
	(*BanUserRequest)(nil),             // 0: varso_auth.BanUserRequest
	(*BanUserResponse)(nil),            // 1: varso_auth.BanUserResponse
	(*DiscordLoginRequest)(nil),        // 2: varso_auth.DiscordLoginRequest
	(*DiscordLoginResponse)(nil),       // 3: varso_auth.DiscordLoginResponse
	(*GetUserResponse)(nil),            // 4: varso_auth.GetUserResponse
	(*GetUserByDiscordIdResponse)(nil), // 5: varso_auth.GetUserByDiscordIdResponse
	(*InternalLoginRequest)(nil),       // 6: varso_auth.InternalLoginRequest
	(*InternalLoginResponse)(nil),      // 7: varso_auth.InternalLoginResponse
	(*RegisterRequest)(nil),            // 8: varso_auth.RegisterRequest
	(*RegisterResponse)(nil),           // 9: varso_auth.RegisterResponse
	(*EasyRegisterRequest)(nil),        // 10: varso_auth.EasyRegisterRequest
	(*EasyRegisterResponse)(nil),       // 11: varso_auth.EasyRegisterResponse
	(*LoginRequest)(nil),               // 12: varso_auth.LoginRequest
	(*LoginResponse)(nil),              // 13: varso_auth.LoginResponse
	(*UnbanUserRequest)(nil),           // 14: varso_auth.UnbanUserRequest
	(*UnbanUserResponse)(nil),          // 15: varso_auth.UnbanUserResponse
	(*User)(nil),                       // 16: varso_auth.User
}
var file_authrequests_proto_depIdxs = []int32{
	16, // 0: varso_auth.GetUserResponse.user:type_name -> varso_auth.User
	16, // 1: varso_auth.GetUserByDiscordIdResponse.user:type_name -> varso_auth.User
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_authrequests_proto_init() }
func file_authrequests_proto_init() {
	if File_authrequests_proto != nil {
		return
	}
	file_authbase_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authrequests_proto_rawDesc), len(file_authrequests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authrequests_proto_goTypes,
		DependencyIndexes: file_authrequests_proto_depIdxs,
		MessageInfos:      file_authrequests_proto_msgTypes,
	}.Build()
	File_authrequests_proto = out.File
	file_authrequests_proto_goTypes = nil
	file_authrequests_proto_depIdxs = nil
}
