// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: appbase.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UniqueName    string                 `protobuf:"bytes,2,opt,name=unique_name,json=uniqueName,proto3" json:"unique_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	WebsiteUrl    string                 `protobuf:"bytes,5,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	LogoImageUrl  string                 `protobuf:"bytes,6,opt,name=logo_image_url,json=logoImageUrl,proto3" json:"logo_image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_appbase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Organization) GetUniqueName() string {
	if x != nil {
		return x.UniqueName
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *Organization) GetLogoImageUrl() string {
	if x != nil {
		return x.LogoImageUrl
	}
	return ""
}

type RSSFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RSSItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSSFeed) Reset() {
	*x = RSSFeed{}
	mi := &file_appbase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSSFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSSFeed) ProtoMessage() {}

func (x *RSSFeed) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSSFeed.ProtoReflect.Descriptor instead.
func (*RSSFeed) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{1}
}

func (x *RSSFeed) GetItems() []*RSSItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RSSItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Link             string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Links            []string               `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	UpdateDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_date,json=updateDate,proto3" json:"update_date,omitempty"`
	PublishDate      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	Authors          []*RSSAuthor           `protobuf:"bytes,8,rep,name=authors,proto3" json:"authors,omitempty"`
	Guid             string                 `protobuf:"bytes,9,opt,name=guid,proto3" json:"guid,omitempty"`
	Image            *RSSImage              `protobuf:"bytes,10,opt,name=image,proto3" json:"image,omitempty"`
	Categories       []string               `protobuf:"bytes,11,rep,name=categories,proto3" json:"categories,omitempty"`
	OrganizationUuid string                 `protobuf:"bytes,12,opt,name=organization_uuid,json=organizationUuid,proto3" json:"organization_uuid,omitempty"`
	Id               string                 `protobuf:"bytes,13,opt,name=id,proto3" json:"id,omitempty"`
	SeeAlsoItem      *RSSItem               `protobuf:"bytes,14,opt,name=see_also_item,json=seeAlsoItem,proto3" json:"see_also_item,omitempty"`
	Rank             int64                  `protobuf:"varint,15,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RSSItem) Reset() {
	*x = RSSItem{}
	mi := &file_appbase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSSItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSSItem) ProtoMessage() {}

func (x *RSSItem) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSSItem.ProtoReflect.Descriptor instead.
func (*RSSItem) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{2}
}

func (x *RSSItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RSSItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RSSItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RSSItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RSSItem) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *RSSItem) GetUpdateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateDate
	}
	return nil
}

func (x *RSSItem) GetPublishDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishDate
	}
	return nil
}

func (x *RSSItem) GetAuthors() []*RSSAuthor {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *RSSItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *RSSItem) GetImage() *RSSImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *RSSItem) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *RSSItem) GetOrganizationUuid() string {
	if x != nil {
		return x.OrganizationUuid
	}
	return ""
}

func (x *RSSItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RSSItem) GetSeeAlsoItem() *RSSItem {
	if x != nil {
		return x.SeeAlsoItem
	}
	return nil
}

func (x *RSSItem) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type RSSAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSSAuthor) Reset() {
	*x = RSSAuthor{}
	mi := &file_appbase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSSAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSSAuthor) ProtoMessage() {}

func (x *RSSAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSSAuthor.ProtoReflect.Descriptor instead.
func (*RSSAuthor) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{3}
}

func (x *RSSAuthor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RSSAuthor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RSSImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Blur          bool                   `protobuf:"varint,3,opt,name=blur,proto3" json:"blur,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSSImage) Reset() {
	*x = RSSImage{}
	mi := &file_appbase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSSImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSSImage) ProtoMessage() {}

func (x *RSSImage) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSSImage.ProtoReflect.Descriptor instead.
func (*RSSImage) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{4}
}

func (x *RSSImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RSSImage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RSSImage) GetBlur() bool {
	if x != nil {
		return x.Blur
	}
	return false
}

var File_appbase_proto protoreflect.FileDescriptor

const file_appbase_proto_rawDesc = "" +
	"\n" +
	"\rappbase.proto\x12\tvarso_app\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\fOrganization\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vunique_name\x18\x02 \x01(\tR\n" +
	"uniqueName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vwebsite_url\x18\x05 \x01(\tR\n" +
	"websiteUrl\x12$\n" +
	"\x0elogo_image_url\x18\x06 \x01(\tR\flogoImageUrl\"3\n" +
	"\aRSSFeed\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.varso_app.RSSItemR\x05items\"\x99\x04\n" +
	"\aRSSItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x14\n" +
	"\x05links\x18\x05 \x03(\tR\x05links\x12;\n" +
	"\vupdate_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateDate\x12=\n" +
	"\fpublish_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vpublishDate\x12.\n" +
	"\aauthors\x18\b \x03(\v2\x14.varso_app.RSSAuthorR\aauthors\x12\x12\n" +
	"\x04guid\x18\t \x01(\tR\x04guid\x12)\n" +
	"\x05image\x18\n" +
	" \x01(\v2\x13.varso_app.RSSImageR\x05image\x12\x1e\n" +
	"\n" +
	"categories\x18\v \x03(\tR\n" +
	"categories\x12+\n" +
	"\x11organization_uuid\x18\f \x01(\tR\x10organizationUuid\x12\x0e\n" +
	"\x02id\x18\r \x01(\tR\x02id\x126\n" +
	"\rsee_also_item\x18\x0e \x01(\v2\x12.varso_app.RSSItemR\vseeAlsoItem\x12\x12\n" +
	"\x04rank\x18\x0f \x01(\x03R\x04rank\"5\n" +
	"\tRSSAuthor\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\bRSSImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04blur\x18\x03 \x01(\bR\x04blurB\x0fZ\rclient/modelsb\x06proto3"

var (
	file_appbase_proto_rawDescOnce sync.Once
	file_appbase_proto_rawDescData []byte
)

func file_appbase_proto_rawDescGZIP() []byte {
	file_appbase_proto_rawDescOnce.Do(func() {
		file_appbase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appbase_proto_rawDesc), len(file_appbase_proto_rawDesc)))
	})
	return file_appbase_proto_rawDescData
}

var file_appbase_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_appbase_proto_goTypes = []any{
	(*Organization)(nil),          // 0: varso_app.Organization
	(*RSSFeed)(nil),               // 1: varso_app.RSSFeed
	(*RSSItem)(nil),               // 2: varso_app.RSSItem
	(*RSSAuthor)(nil),             // 3: varso_app.RSSAuthor
	(*RSSImage)(nil),              // 4: varso_app.RSSImage
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_appbase_proto_depIdxs = []int32{
	2, // 0: varso_app.RSSFeed.items:type_name -> varso_app.RSSItem
	5, // 1: varso_app.RSSItem.update_date:type_name -> google.protobuf.Timestamp
	5, // 2: varso_app.RSSItem.publish_date:type_name -> google.protobuf.Timestamp
	3, // 3: varso_app.RSSItem.authors:type_name -> varso_app.RSSAuthor
	4, // 4: varso_app.RSSItem.image:type_name -> varso_app.RSSImage
	2, // 5: varso_app.RSSItem.see_also_item:type_name -> varso_app.RSSItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_appbase_proto_init() }
func file_appbase_proto_init() {
	if File_appbase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appbase_proto_rawDesc), len(file_appbase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appbase_proto_goTypes,
		DependencyIndexes: file_appbase_proto_depIdxs,
		MessageInfos:      file_appbase_proto_msgTypes,
	}.Build()
	File_appbase_proto = out.File
	file_appbase_proto_goTypes = nil
	file_appbase_proto_depIdxs = nil
}
