// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: apprequests.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationsResponse) Reset() {
	*x = GetOrganizationsResponse{}
	mi := &file_apprequests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationsResponse) ProtoMessage() {}

func (x *GetOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apprequests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_apprequests_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

type GetNewsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Organizations map[string]*Organization `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Featured      *RSSItem                 `protobuf:"bytes,2,opt,name=featured,proto3" json:"featured,omitempty"`
	Latest        *RSSFeed                 `protobuf:"bytes,3,opt,name=latest,proto3" json:"latest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsResponse) Reset() {
	*x = GetNewsResponse{}
	mi := &file_apprequests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsResponse) ProtoMessage() {}

func (x *GetNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apprequests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsResponse.ProtoReflect.Descriptor instead.
func (*GetNewsResponse) Descriptor() ([]byte, []int) {
	return file_apprequests_proto_rawDescGZIP(), []int{1}
}

func (x *GetNewsResponse) GetOrganizations() map[string]*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *GetNewsResponse) GetFeatured() *RSSItem {
	if x != nil {
		return x.Featured
	}
	return nil
}

func (x *GetNewsResponse) GetLatest() *RSSFeed {
	if x != nil {
		return x.Latest
	}
	return nil
}

type BlurToggleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RssItemId     string                 `protobuf:"bytes,1,opt,name=rss_item_id,json=rssItemId,proto3" json:"rss_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlurToggleRequest) Reset() {
	*x = BlurToggleRequest{}
	mi := &file_apprequests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlurToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlurToggleRequest) ProtoMessage() {}

func (x *BlurToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apprequests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlurToggleRequest.ProtoReflect.Descriptor instead.
func (*BlurToggleRequest) Descriptor() ([]byte, []int) {
	return file_apprequests_proto_rawDescGZIP(), []int{2}
}

func (x *BlurToggleRequest) GetRssItemId() string {
	if x != nil {
		return x.RssItemId
	}
	return ""
}

type DeleteNewsItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RssItemId     string                 `protobuf:"bytes,1,opt,name=rss_item_id,json=rssItemId,proto3" json:"rss_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNewsItemRequest) Reset() {
	*x = DeleteNewsItemRequest{}
	mi := &file_apprequests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNewsItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNewsItemRequest) ProtoMessage() {}

func (x *DeleteNewsItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apprequests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNewsItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteNewsItemRequest) Descriptor() ([]byte, []int) {
	return file_apprequests_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteNewsItemRequest) GetRssItemId() string {
	if x != nil {
		return x.RssItemId
	}
	return ""
}

var File_apprequests_proto protoreflect.FileDescriptor

const file_apprequests_proto_rawDesc = "" +
	"\n" +
	"\x11apprequests.proto\x12\tvarso_app\x1a\rappbase.proto\"Y\n" +
	"\x18GetOrganizationsResponse\x12=\n" +
	"\rorganizations\x18\x01 \x03(\v2\x17.varso_app.OrganizationR\rorganizations\"\x9d\x02\n" +
	"\x0fGetNewsResponse\x12S\n" +
	"\rorganizations\x18\x01 \x03(\v2-.varso_app.GetNewsResponse.OrganizationsEntryR\rorganizations\x12.\n" +
	"\bfeatured\x18\x02 \x01(\v2\x12.varso_app.RSSItemR\bfeatured\x12*\n" +
	"\x06latest\x18\x03 \x01(\v2\x12.varso_app.RSSFeedR\x06latest\x1aY\n" +
	"\x12OrganizationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.varso_app.OrganizationR\x05value:\x028\x01\"3\n" +
	"\x11BlurToggleRequest\x12\x1e\n" +
	"\vrss_item_id\x18\x01 \x01(\tR\trssItemId\"7\n" +
	"\x15DeleteNewsItemRequest\x12\x1e\n" +
	"\vrss_item_id\x18\x01 \x01(\tR\trssItemIdB\x0fZ\rclient/modelsb\x06proto3"

var (
	file_apprequests_proto_rawDescOnce sync.Once
	file_apprequests_proto_rawDescData []byte
)

func file_apprequests_proto_rawDescGZIP() []byte {
	file_apprequests_proto_rawDescOnce.Do(func() {
		file_apprequests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apprequests_proto_rawDesc), len(file_apprequests_proto_rawDesc)))
	})
	return file_apprequests_proto_rawDescData
}

var file_apprequests_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apprequests_proto_goTypes = []any{
	(*GetOrganizationsResponse)(nil), // 0: varso_app.GetOrganizationsResponse
	(*GetNewsResponse)(nil),          // 1: varso_app.GetNewsResponse
	(*BlurToggleRequest)(nil),        // 2: varso_app.BlurToggleRequest
	(*DeleteNewsItemRequest)(nil),    // 3: varso_app.DeleteNewsItemRequest
	nil,                              // 4: varso_app.GetNewsResponse.OrganizationsEntry
	(*Organization)(nil),             // 5: varso_app.Organization
	(*RSSItem)(nil),                  // 6: varso_app.RSSItem
	(*RSSFeed)(nil),                  // 7: varso_app.RSSFeed
}
var file_apprequests_proto_depIdxs = []int32{
	5, // 0: varso_app.GetOrganizationsResponse.organizations:type_name -> varso_app.Organization
	4, // 1: varso_app.GetNewsResponse.organizations:type_name -> varso_app.GetNewsResponse.OrganizationsEntry
	6, // 2: varso_app.GetNewsResponse.featured:type_name -> varso_app.RSSItem
	7, // 3: varso_app.GetNewsResponse.latest:type_name -> varso_app.RSSFeed
	5, // 4: varso_app.GetNewsResponse.OrganizationsEntry.value:type_name -> varso_app.Organization
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_apprequests_proto_init() }
func file_apprequests_proto_init() {
	if File_apprequests_proto != nil {
		return
	}
	file_appbase_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apprequests_proto_rawDesc), len(file_apprequests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apprequests_proto_goTypes,
		DependencyIndexes: file_apprequests_proto_depIdxs,
		MessageInfos:      file_apprequests_proto_msgTypes,
	}.Build()
	File_apprequests_proto = out.File
	file_apprequests_proto_goTypes = nil
	file_apprequests_proto_depIdxs = nil
}
