version: '3.9'
services:
  auth:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: goappapi
      args:
        SERVICE: auth
        PORT: 5004
    env_file:
      - .env
    ports:
      - 5004:5004
    networks:
      - bridge_network
    restart: always

  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: goappapi
      args:
        SERVICE: app
        PORT: 5001
    env_file:
      - .env
    ports:
      - 5001:5001
    networks:
      - bridge_network
    restart: always
  
  fileserver:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: goappapi
      args:
        SERVICE: fileserver
        PORT: 5002
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 5002:5002
    networks:
      - bridge_network
    restart: always


networks:
  bridge_network:
    driver: bridge

volumes:
  filestorage:
  letsencrypt:
  alertmanager:
  certbotdata:
  db-data:
    driver: local
  event-data:
    driver: local